### ISSUE TITLE
[Spec] How to get parent block in LMD Ghost?

### ISSUE THREAD

**Issue by yudetamago** [LayerXcom/cbc-beacon-chain#4]
<img width="647" alt="ss" src="https://user-images.githubusercontent.com/1025957/53323800-83895e80-3922-11e9-855c-7f45769a534a.png">

In original paper, `prev` function is defined.
We use this with `estimate` (consensus value) from received message?

**Comment by yudetamago** [comment]
Like message's justification, we can extract block from message history in receiver.
Note: For optimization, some additional fields like `last_justified_estimate` are needed.

**Comment by nrryuya** [comment]
I think about this issue CBC is not so different from other protocols? We just store blockchain in the client and look that when we check fork choice.

**Comment by yudetamago** [comment]
Yeah I think so too.
To check fork choice, we can do it just by using message history in receiver (if we can know other validators' weight when the estimate was made.).
