### ISSUE TITLE
How to represent the recursive structure of `Message` and `Block` in implementation?

### ISSUE THREAD

**Issue by yudetamago** [LayerXcom/cbc-beacon-chain#5]
In the paper

* Each `Message` has its `justification` and
* Each `Block` has its parent block

but in the view of data amount efficiency and computational efficiency, sending all recursived data is unrealistic.
Some form of serialization or hashing is needed?

**Comment by nrryuya** [comment]
About block, CBC is not so different from other protocols. We can simply include the parent hash in the block. If the message itself is not "pending", then the fork choice won't select unknown block.

**Comment by nrryuya** [comment]
About messages, this issue is duplicate of #1 ?

**Comment by yudetamago** [comment]
Yep! Storing parent hash in each block (without genesis) is concise.
Close this issue.
